/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BenitesMenu {
        "cartContentsCount": number;
    }
    interface BenitesStarsInput {
    }
    interface BenitesStarsRating {
    }
}
declare global {
    interface HTMLBenitesMenuElement extends Components.BenitesMenu, HTMLStencilElement {
    }
    var HTMLBenitesMenuElement: {
        prototype: HTMLBenitesMenuElement;
        new (): HTMLBenitesMenuElement;
    };
    interface HTMLBenitesStarsInputElement extends Components.BenitesStarsInput, HTMLStencilElement {
    }
    var HTMLBenitesStarsInputElement: {
        prototype: HTMLBenitesStarsInputElement;
        new (): HTMLBenitesStarsInputElement;
    };
    interface HTMLBenitesStarsRatingElement extends Components.BenitesStarsRating, HTMLStencilElement {
    }
    var HTMLBenitesStarsRatingElement: {
        prototype: HTMLBenitesStarsRatingElement;
        new (): HTMLBenitesStarsRatingElement;
    };
    interface HTMLElementTagNameMap {
        "benites-menu": HTMLBenitesMenuElement;
        "benites-stars-input": HTMLBenitesStarsInputElement;
        "benites-stars-rating": HTMLBenitesStarsRatingElement;
    }
}
declare namespace LocalJSX {
    interface BenitesMenu {
        "cartContentsCount"?: number;
    }
    interface BenitesStarsInput {
    }
    interface BenitesStarsRating {
    }
    interface IntrinsicElements {
        "benites-menu": BenitesMenu;
        "benites-stars-input": BenitesStarsInput;
        "benites-stars-rating": BenitesStarsRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "benites-menu": LocalJSX.BenitesMenu & JSXBase.HTMLAttributes<HTMLBenitesMenuElement>;
            "benites-stars-input": LocalJSX.BenitesStarsInput & JSXBase.HTMLAttributes<HTMLBenitesStarsInputElement>;
            "benites-stars-rating": LocalJSX.BenitesStarsRating & JSXBase.HTMLAttributes<HTMLBenitesStarsRatingElement>;
        }
    }
}
